using Distributions
import .ScottishLowerProtocol: AbstractSLModelAdapter,sl_model,sl_model_name,sl_required_features,sl_assert_model_contract,sl_build_turing_model,sl_params_from_varinfo,sl_equation_data,sl_equation_logjoint,sl_sampled_sites,sl_parameter_row,sl_synthetic_n_teams,sl_synthetic_draws,sl_synthetic_fixtures,sl_reference_extract,sl_extract_parameters,sl_extract_params,sl_compute_score_matrix,sl_reference_grid,sl_marginal_cdf_bounds,sl_marginal_logpdf,sl_capabilities,sl_referee_eval,sl_result
struct TP04Adapter{M<:DynamicPoissonWealthDistanceGoalsTimeDecayModel} <: AbstractSLModelAdapter; model::M end
TP04Adapter(;kwargs...)=TP04Adapter(tp04_model(;kwargs...)); sl_model(a::TP04Adapter)=a.model; sl_model_name(::TP04Adapter)="04_poisson_wealth_distance"; sl_required_features(a::TP04Adapter)=SLFP_Features.required_features(a.model)
function sl_assert_model_contract(a::TP04Adapter); m=a.model; m.interception_config isa SLFP_PG.GlobalInterception&&m.homeadvantage_config isa SLFP_PG.GlobalHomeAdvantage&&m.dynamics_config isa SLFP_PG.TimeDecayDynamics&&m.wealth_feature isa SLFPLogSumWealthFeature&&m.distance_feature isa ScottishDistanceFeature&&m.distance_feature.metric==:log_dist_z&&m.w_wealth_prior==truncated(Normal(.10,.05),lower=0.)&&m.w_dist_prior==truncated(Normal(.04,.03),lower=0.)||error("TP04 default contract violated"); true end
sl_build_turing_model(a::TP04Adapter,fs)=SLFP_PG.build_turing_model(a.model,fs); sl_params_from_varinfo(a::TP04Adapter,vi)=slfp_params(a.model,vi); sl_equation_data(a::TP04Adapter,fs)=tp04_equation_data(a.model,fs); sl_equation_logjoint(a::TP04Adapter,p,d)=tp04_logjoint(a.model,p,d)
sl_sampled_sites(::TP04Adapter,n)=vcat(["inter.μ","ha.γ_global","dyn.σ_a","dyn.σ_d","w_wealth","w_dist"],["dyn.raw_a[$i]" for i=1:n],["dyn.raw_d[$i]" for i=1:n]); sl_parameter_row(::TP04Adapter,p)=vcat(p.μ,p.γ,p.σ_a,p.σ_d,p.w_wealth,p.w_dist,p.raw_a,p.raw_d); sl_synthetic_n_teams(::TP04Adapter,p)=length(p.raw_a)
function sl_synthetic_draws(a::TP04Adapter,n,k;seed=1); rng=MersenneTwister(seed); [SLFPParams(μ=.2,γ=.2,σ_a=.2,σ_d=.2,raw_a=randn(rng,n),raw_d=randn(rng,n),w_wealth=.1+.01i,w_dist=.04+.01i) for i=1:k] end
function sl_synthetic_fixtures(::TP04Adapter,tm;n=6,unmapped=false); t=collect(keys(tm)); h=[t[mod1(i,length(t))] for i=1:n]; a=[t[mod1(i+1,length(t))] for i=1:n]; unmapped&&(h[end]="__unknown__"); DataFrame(match_id=1:n,home_team=h,away_team=a,match_date=fill(Date(2024,1,1),n),season_idx=fill(1,n),delta_wealth_logsum=[unmapped&&i==n ? 0. : (-1)^i*.3 for i=1:n],wealth_fallback=[unmapped&&i==n ? 1 : 0 for i=1:n],distance_z=[unmapped&&i==n ? 0. : .2 for i=1:n],distance_fallback=[unmapped&&i==n ? 1 : 0 for i=1:n]) end
function sl_reference_extract(a::TP04Adapter,p,r,fs); α,β=slfp_team_effects(p); h=get(fs.data[:team_map],r.home_team,0); aw=get(fs.data[:team_map],r.away_team,0); q=p.w_wealth*r.delta_wealth_logsum+p.w_dist*r.distance_z; eh=clamp(p.μ+p.γ+(h>0 ? α[h] : 0.)+(aw>0 ? β[aw] : 0.)+q,-10.,10.); ea=clamp(p.μ+(aw>0 ? α[aw] : 0.)+(h>0 ? β[h] : 0.)-q,-10.,10.); (λ_h=exp(eh),λ_a=exp(ea),true_xg_h=exp(eh),true_xg_a=exp(ea)) end
sl_extract_parameters(a::TP04Adapter,df,fs,ch)=SLFP_PG.extract_parameters(a.model,df,fs,ch); sl_extract_params(a::TP04Adapter,r)=BayesianFootball.Predictions.extract_params(a.model,r); sl_compute_score_matrix(a::TP04Adapter,p;max_goals=12)=BayesianFootball.Predictions.compute_score_matrix(a.model,p;max_goals)
sl_reference_grid(::TP04Adapter,r,k,g)=[pdf(Poisson(r.λ_h[k]),i)*pdf(Poisson(r.λ_a[k]),j) for i=0:g-1,j=0:g-1]; sl_marginal_cdf_bounds(::TP04Adapter,s,r,y)=error("unused"); sl_marginal_logpdf(::TP04Adapter,s,r,y)=error("unused")
function sl_capabilities(a::TP04Adapter); (;expected_score_dispatch="l03_adapter.jl",posterior_schema=(;varinfo_sites=("inter.μ","ha.γ_global","dyn.σ_a","dyn.σ_d","w_wealth","w_dist","dyn.raw_a","dyn.raw_d"),chain_columns=n->sl_sampled_sites(a,n),parameter_count=n->6+2n),extraction_schema=(;posterior_fields=(:λ_h,:λ_a,:true_xg_h,:true_xg_a),positive_fields=(:λ_h,:λ_a,:true_xg_h,:true_xg_a)),funnel_sites=("dyn.σ_a","dyn.σ_d"),score_matrix_normalized=false) end
function sl_referee_eval(a::TP04Adapter,s::Symbol,args...); s==:config ? [sl_result("active wealth coefficient",true,"w_wealth only")] : NamedTuple[] end